### ISSUE TITLE
Https Proxy: Support attaching managed ssl certs

### ISSUE THREAD

**Issue by RichieHowell** [perfectsense/gyro-google-provider#152]
Currently, we cannot create managed certs through gyro because the REST API does not have the ability to do so. Through the console though, one can be created. The https proxy should be updated so that the "sslCertificates" variable is a list of strings instead of ssl certificates, and those strings are self links to certificates. 

This would allow me to create a GCP managed certificate in the console, update the gyro file with the self link, and have gyro not replace my managed cert.

To expand on managed certs not being supported in REST API, [this link](https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates?hl=en_US) would need to have an attribute for "type" which can be set to managed, which it does not. Also, [the docs to create them](https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs) has no API tab.

**Comment by deepanjan90** [comment]
The list of `sslSertificateResource` that the `targetProxy` accepts, can also handle supplying just the `selfLink` as that is the field annotated with `@Id` and is sufficient enough to fulfill the reference
