### ISSUE TITLE
Instance Templates and Instances : Make disk name not required.

### ISSUE THREAD

**Issue by RichieHowell** [perfectsense/gyro-google-provider#154]
On the docs here https://cloud.google.com/compute/docs/reference/rest/v1/instances and https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates, the disk name for initialize parameters say that if they are not specified, the instance name will be used instead. I need to use this for instance templates specifically as if I try to launch 4 autoscale instances, the 4th fails to start as it must share the same zone with another and fails to start due to boot disk name being the same as the other in the zone. 

The required tag should be removed from disk names on InstanceAttachedDiskInitializeParams.

**Comment by sshyub** [comment]
Anyone who is going to address this issue should not simply remove the annotation since it's being used as a primary key.
