### ISSUE TITLE
GCP: VM instance

### ISSUE THREAD

**Issue by kluman** [perfectsense/gyro-google-provider#22]
> Compute Engine lets you use virtual machines that run on Google's infrastructure. Create micro-VMs or larger instances running Debian, Windows, or other standard images. Create your first VM instance, import it using a migration service, or try the quickstart to build a sample app.

This is the instances API: https://cloud.google.com/compute/docs/reference/rest/v1/instances

<img width="1132" alt="instances" src="https://user-images.githubusercontent.com/286670/68052739-b4474200-fcc0-11e9-81d5-3a72c792f7a5.png">

**Comment by deepanjan90** [comment]
Add reference to the following resource:
 - Route Resource (`nextHopInstance`)
 - Network Endpoint Resource (`endpointGroup` --> `instance`)
