### ISSUE TITLE
GCP: All compute operations should wait for successful execution

### ISSUE THREAD

**Issue by deepanjan90** [perfectsense/gyro-google-provider#30]
All compute operations (create, modify, delete) should wait for the status of the operation to `done`. Some operations like network delete, might fail without an error, unless the specifically the operation status is checked, which on failure will contain  the error.

Example if a Network resource is created and managed via gyro, but some other resource is created referencing this network, if the network is deleted by gyro when the other resource referencing this network exists, gyro would show ok, but the network would still exist.

**Comment by beetlebugorg** [comment]
This keeps falling behind because it changed the method signature. How do we work this in quickly?

**Comment by deepanjan90** [comment]
Updated with the latest changes. This should get merged as nothing else in the `ready to merge` pipeline
