### ISSUE TITLE
GCP: Snapshots

### ISSUE THREAD

**Issue by alex-lambrides** [perfectsense/gyro-google-provider#54]
https://cloud.google.com/compute/docs/reference/rest/v1/snapshots

<img width="1081" alt="GCP-Snapshots" src="https://user-images.githubusercontent.com/41128683/69977524-f7334a00-14f8-11ea-8591-4397d1bcebc9.png">

**Comment by deepanjan90** [comment]
Depends on #21

**Comment by deepanjan90** [comment]
Duplicate #62
