### ISSUE TITLE
GCP: Managed Instance Groups

### ISSUE THREAD

**Issue by jpencola** [perfectsense/gyro-google-provider#59]
> An instance group is a collection of virtual machine (VM) instances that you can manage as a single entity.

> Compute Engine offers two kinds of VM instance groups, managed and unmanaged:

> Managed instance groups (MIGs) let you operate apps on multiple identical VMs. You can make your workloads scalable and highly available by taking advantage of automated MIG services, including: autoscaling, autohealing, regional (multiple zone) deployment, and automatic updating.

This uses the Instance Group Manager API: https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers

This work should also include support for the Region Instance Group Manager API:
https://cloud.google.com/compute/docs/reference/rest/v1/regionInstanceGroupManagers

![image](https://user-images.githubusercontent.com/102225/70171643-21be0800-169d-11ea-97a0-d29a0d64025d.png)

**Comment by sshyub** [comment]
PR: https://github.com/perfectsense/gyro-google-provider/pull/96
