### ISSUE TITLE
GCP: Image

### ISSUE THREAD

**Issue by kluman** [perfectsense/gyro-google-provider#61]
> Use operating system images to create boot disks for your instances. You can use one of the following image types:
> 
> Public images are provided and maintained by Google, open-source communities, and third-party vendors. By default, all projects have access to these images and can use them to create instances.
> 
> Custom images are available only to your project. You can create a custom image from boot disks and other images. Then, use the custom image to create an instance.

API
https://cloud.google.com/compute/docs/reference/rest/v1/images

![Create Image](https://user-images.githubusercontent.com/286670/70264313-31edea00-1766-11ea-885e-cae82269a6b8.png)

**Comment by kluman** [comment]
InstanceAttachedDiskInitializeParams should be updated to include sourceImage field when done.

**Comment by alex-lambrides** [comment]
Image should be added to Disk (#21) when it is implemented.
