### ISSUE TITLE
GCP: Snapshot

### ISSUE THREAD

**Issue by kluman** [perfectsense/gyro-google-provider#62]
Represents a Persistent Disk Snapshot resource.

> Create snapshots to periodically back up data from your zonal persistent disks or regional persistent disks. To reduce the risk of unexpected data loss, consider the best practice of setting up a snapshot schedule to ensure your data is backed up on a regular schedule.

API:
https://cloud.google.com/compute/docs/reference/rest/v1/snapshots

![Snapshot](https://user-images.githubusercontent.com/286670/70265999-9cecf000-1769-11ea-9d2d-119a197ab434.jpg)

**Comment by kluman** [comment]
Update InstanceAttachedDiskInitializeParams with sourceSnapshot field when done.

**Comment by deepanjan90** [comment]
depends on #21
